LINK VIDEO GOOGLE DRIVE:

No 1 : https://drive.google.com/file/d/1HiUymQaMJ9d8gHEQVrqdyLFP7JDcwYUi/view?usp=drive_link

No 2 : https://drive.google.com/file/d/1TJbTbz0n7gKaoeZExK6dMZHTjS4bw4BB/view?usp=drive_link

No 3 : https://drive.google.com/file/d/1e1W1YgUNfTjv__x0Sm34cEI55jpjqQ5L/view?usp=drive_link

No 4 : https://drive.google.com/file/d/1bm9LYh02JL5gowSf2jYVceGUJyxo1wpS/view?usp=drive_link

In [ ]:
import numpy as np

# 1. Inisialisasi Data & Parameter
# Input (I1, I2)
X = np.array([1.0, -2.0])
y_target = 1.0
lr = 0.01

# Bobot Layer 1 (Hidden 1) - Bentuk (input, output_neurons)
# Kolom 0: H1_1, Kolom 1: H1_2, Kolom 2: H1_3
W_h1 = np.array([
    [2.0, -1.0,  1.0],  # Dari I1 (W1, W2, W3)
    [1.0, -2.0, -1.0]   # Dari I2 (W4, W5, W6)
])

# Bobot Layer 2 (Hidden 2)
# Baris: input dari H1, Kolom: neuron H2
W_h2 = np.array([
    [ 1.0,  3.0], # Dari H1_1 (W1_h2, W2_h2)
    [-2.0,  1.0], # Dari H1_2 (W3_h2, W4_h2)
    [ 2.0, -2.0]  # Dari H1_3 (W5_h2, W6_h2)
])

# Bobot Output Layer
W_o = np.array([-2.0, 3.0])

# Bias untuk semua neuron = 1
b_h1 = np.ones(3)
b_h2 = np.ones(2)
b_o = 1.0

def relu(z):
    return np.maximum(0, z)

def relu_prime(z):
    return (z > 0).astype(float)

# FORWARD PASS
print("FORWARD PASS")
# Hidden 1
z_h1 = np.dot(X, W_h1) + b_h1
a_h1 = relu(z_h1)
print(f"z_H1: {z_h1} | a_H1: {a_h1}")

# Hidden 2
z_h2 = np.dot(a_h1, W_h2) + b_h2
a_h2 = relu(z_h2)
print(f"z_H2: {z_h2} | a_H2: {a_h2}")

# Output
z_o = np.dot(a_h2, W_o) + b_o
y_pred = z_o # Linear activation
print(f"z_O (y_pred): {y_pred}")

# Loss (MSE: 0.5 * (y - y_hat)^2)
loss = 0.5 * (y_target - y_pred)**2
print(f"Loss: {loss}\n")

# BACKWARD PASS
print("BACKWARD PASS (Gradients)")
# Gradien Output Layer
# dL/dz_o = (y_pred - y_target)
delta_o = (y_pred - y_target)
dW_o = delta_o * a_h2
db_o = delta_o
print(f"delta_O: {delta_o}")
print(f"dW_O: {dW_o}")

# Gradien Hidden Layer 2
# delta_h2 = (delta_o * W_o) * ReLU'(z_h2)
delta_h2 = (delta_o * W_o) * relu_prime(z_h2)
dW_h2 = np.outer(a_h1, delta_h2)
print(f"delta_H2: {delta_h2}")
print(f"dW_H2:\n{dW_h2}")

# Gradien Hidden Layer 1
# delta_h1 = (delta_h2 * W_h2.T) * ReLU'(z_h1)
delta_h1 = np.dot(delta_h2, W_h2.T) * relu_prime(z_h1)
dW_h1 = np.outer(X, delta_h1)
print(f"delta_H1: {delta_h1}")
print(f"dW_H1:\n{dW_h1}\n")

# UPDATE WEIGHTS
print("UPDATED WEIGHTS (After 1 Step)")
W_o_new = W_o - lr * dW_o
W_h2_new = W_h2 - lr * dW_h2
W_h1_new = W_h1 - lr * dW_h1

print(f"W_O Updated: {W_o_new}")
print(f"W_H2 Updated:\n{W_h2_new}")
print(f"W_H1 Updated:\n{W_h1_new}")

FORWARD PASS
z_H1: [1. 4. 4.] | a_H1: [1. 4. 4.]
z_H2: [2. 0.] | a_H2: [2. 0.]
z_O (y_pred): -3.0
Loss: 8.0

BACKWARD PASS (Gradients)
delta_O: -4.0
dW_O: [-8. -0.]
delta_H2: [ 8. -0.]
dW_H2:
[[ 8. -0.]
 [32. -0.]
 [32. -0.]]
delta_H1: [  8. -16.  16.]
dW_H1:
[[  8. -16.  16.]
 [-16.  32. -32.]]

UPDATED WEIGHTS (After 1 Step)
W_O Updated: [-1.92  3.  ]
W_H2 Updated:
[[ 0.92  3.  ]
 [-2.32  1.  ]
 [ 1.68 -2.  ]]
W_H1 Updated:
[[ 1.92 -0.84  0.84]
 [ 1.16 -2.32 -0.68]]
